export const contrysList = [
  { txt: 'Afghanistan' },
  { txt: 'Albania' },
  { txt: 'Algeria' },
  { txt: 'American Samoa' },
  { txt: 'Andorra' },
  { txt: 'Angola' },
  { txt: 'Anguilla' },
  { txt: 'Antarctica' },
  { txt: 'Antigua and Barbuda' },
  { txt: 'Argentina' },
  { txt: 'Armenia' },
  { txt: 'Aruba' },
  { txt: 'Australia' },
  { txt: 'Austria' },
  { txt: 'Azerbaijan' },
  { txt: 'Bahamas' },
  { txt: 'Bahrain' },
  { txt: 'Bangladesh' },
  { txt: 'Barbados' },
  { txt: 'Belarus' },
  { txt: 'Belgium' },
  { txt: 'Belize' },
  { txt: 'Benin' },
  { txt: 'Bermuda' },
  { txt: 'Bhutan' },
  { txt: 'Bolivia' },
  { txt: 'Bonaire, Sint Eustatius and Saba' },
  { txt: 'Bosnia and Herzegovina' },
  { txt: 'Botswana' },
  { txt: 'Bouvet Island' },
  { txt: 'Brazil' },
  { txt: 'British Indian Ocean Territory' },
  { txt: 'Brunei Darussalam' },
  { txt: 'Bulgaria' },
  { txt: 'Burkina Faso' },
  { txt: 'Burundi' },
  { txt: 'Cabo Verde' },
  { txt: 'Cambodia' },
  { txt: 'Cameroon' },
  { txt: 'Canada' },
  { txt: 'Cayman Islands' },
  { txt: 'Central African Republic' },
  { txt: 'Chad' },
  { txt: 'Chile' },
  { txt: 'China' },
  { txt: 'Christmas Island' },
  { txt: 'Cocos (Keeling) Islands' },
  { txt: 'Colombia' },
  { txt: 'Comoros' },
  { txt: 'Congo' },
  { txt: 'Congo, The Democratic Republic of the' },
  { txt: 'Cook Islands' },
  { txt: 'Costa Rica' },
  {
    txt: `Côte d'Ivoire`
  },
  { txt: 'Croatia' },
  { txt: 'Cuba' },
  { txt: 'Curaçao' },
  { txt: 'Cyprus' },
  { txt: 'Czechia' },
  { txt: 'Denmark' },
  { txt: 'Djibouti' },
  { txt: 'Dominica' },
  { txt: 'Dominican Republic' },
  { txt: 'Ecuador' },
  { txt: 'Egypt' },
  { txt: 'El Salvador' },
  { txt: 'Equatorial Guinea' },
  { txt: 'Eritrea' },
  { txt: 'Estonia' },
  { txt: 'Eswatini' },
  { txt: 'Ethiopia' },
  { txt: 'Falkland Islands (Malvinas)' },
  { txt: 'Faroe Islands' },
  { txt: 'Fiji' },
  { txt: 'Finland' },
  { txt: 'France' },
  { txt: 'French Guiana' },
  { txt: 'French Polynesia' },
  { txt: 'French Southern Territories' },
  { txt: 'Gabon' },
  { txt: 'Gambia' },
  { txt: 'Georgia' },
  { txt: 'Germany' },
  { txt: 'Ghana' },
  { txt: 'Gibraltar' },
  { txt: 'Greece' },
  { txt: 'Greenland' },
  { txt: 'Grenada' },
  { txt: 'Guam' },
  { txt: 'Guatemala' },
  { txt: 'Guernsey' },
  { txt: 'Guinea' },
  { txt: 'Guinea-Bissau' },
  { txt: 'Guyana' },
  { txt: 'Haiti' },
  { txt: 'Heard Island and McDonald Islands' },
  { txt: 'Holy See (Vatican City State)' },
  { txt: 'Honduras' },
  { txt: 'Hong Kong' },
  { txt: 'Hungary' },
  { txt: 'Iceland' },
  { txt: 'India' },
  { txt: 'Indonesia' },
  { txt: 'Iran' },
  { txt: 'Iraq' },
  { txt: 'Ireland' },
  { txt: 'Isle of Man' },
  { txt: 'Israel' },
  { txt: 'Italy' },
  { txt: 'Jamaica' },
  { txt: 'Japan' },
  { txt: 'Jersey' },
  { txt: 'Jordan' },
  { txt: 'Kazakhstan' },
  { txt: 'Kenya' },
  { txt: 'Kiribati' },
  { txt: `Korea, Democratic People's Republic of` },
  { txt: 'Korea, Republic of' },
  { txt: 'Kuwait' },
  { txt: 'Kyrgyzstan' },
  {
    txt: `Lao People's Democratic Republic`
  },
  { txt: 'Latvia' },
  { txt: 'Lebanon' },
  { txt: 'Lesotho' },
  { txt: 'Liberia' },
  { txt: 'Libya' },
  { txt: 'Liechtenstein' },
  { txt: 'Lithuania' },
  { txt: 'Luxembourg' },
  { txt: 'Macao' },
  { txt: 'Madagascar' },
  { txt: 'Malawi' },
  { txt: 'Malaysia' },
  { txt: 'Maldives' },
  { txt: 'Mali' },
  { txt: 'Malta' },
  { txt: 'Marshall Islands' },
  { txt: 'Mauritania' },
  { txt: 'Mauritius' },
  { txt: 'Mexico' },
  { txt: 'Micronesia, Federated States of' },
  { txt: 'Moldova' },
  { txt: 'Monaco' },
  { txt: 'Mongolia' },
  { txt: 'Montenegro' },
  { txt: 'Montserrat' },
  { txt: 'Morocco' },
  { txt: 'Mozambique' },
  { txt: 'Myanmar' },
  { txt: 'Namibia' },
  { txt: 'Nauru' },
  { txt: 'Nepal' },
  { txt: 'Netherlands' },
  { txt: 'New Caledonia' },
  { txt: 'New Zealand' },
  { txt: 'Nicaragua' },
  { txt: 'Niger' },
  { txt: 'Nigeria' },
  { txt: 'Niue' },
  { txt: 'Norfolk Island' },
  { txt: 'North Macedonia' },
  { txt: 'Northern Mariana Islands' },
  { txt: 'Norway' },
  { txt: 'Oman' },
  { txt: 'Pakistan' },
  { txt: 'Palau' },
  { txt: 'Palestine, State of' },
  { txt: 'Panama' },
  { txt: 'Papua New Guinea' },
  { txt: 'Paraguay' },
  { txt: 'Peru' },
  { txt: 'Philippines' },
  { txt: 'Pitcairn' },
  { txt: 'Poland' },
  { txt: 'Portugal' },
  { txt: 'Puerto Rico' },
  { txt: 'Qatar' },
  { txt: 'Romania' },
  { txt: 'Russia' },
  { txt: 'Rwanda' },
  // { txt: 'Saint Helena, Ascension and Tristan da Cunha' },
  { txt: 'Saint Helena' },
  { txt: 'Sain' },
  { txt: 'Saint Kitts and Nevis' },
  { txt: 'Saint Lucia' },
  { txt: 'Saint Martin (French part)' },
  { txt: 'Saint Pierre and Miquelon' },
  { txt: 'Saint Vincent and the Grenadines' },
  { txt: 'Samoa' },
  { txt: 'San Marino' },
  { txt: 'Sao Tome and Principe' },
  { txt: 'Saudi Arabia' },
  { txt: 'Senegal' },
  { txt: 'Serbia' },
  { txt: 'Seychelles' },
  { txt: 'Sierra Leone' },
  { txt: 'Singapore' },
  { txt: 'Sint Maarten (Dutch part)' },
  { txt: 'Slovakia' },
  { txt: 'Slovenia' },
  { txt: 'Solomon Islands' },
  { txt: 'Somalia' },
  { txt: 'South Africa' },
  // { txt: 'South Georgia and the South Sandwich Islands' },
  { txt: 'SGSSI' },
  { txt: 'South Sudan' },
  { txt: 'Spain' },
  { txt: 'Sri Lanka' },
  { txt: 'Sudan' },
  { txt: 'Suriname' },
  { txt: 'Svalbard and Jan Mayen' },
  { txt: 'Sweden' },
  { txt: 'Switzerland' },
  { txt: 'Syria' },
  // { txt: 'Taiwan' },
  { txt: 'Tajikistan' },
  { txt: 'Tanzania' },
  { txt: 'Thailand' },
  { txt: 'Timor-Leste' },
  { txt: 'Togo' },
  { txt: 'Tokelau' },
  { txt: 'Tonga' },
  { txt: 'Trinidad and Tobago' },
  { txt: 'Tunisia' },
  { txt: 'Turkey' },
  { txt: 'Turkmenistan' },
  { txt: 'Turks and Caicos Islands' },
  { txt: 'Tuvalu' },
  { txt: 'Uganda' },
  { txt: 'Ukraine' },
  { txt: 'United Arab Emirates' },
  { txt: 'United Kingdom' },
  { txt: 'United States' },
  { txt: 'United States Minor Outlying Islands' },
  { txt: 'Uruguay' },
  { txt: 'Uzbekistan' },
  { txt: 'Vanuatu' },
  { txt: 'Venezuela' },
  { txt: 'Vietnam' },
  { txt: 'Virgin Islands, British' },
  { txt: 'Virgin Islands, U.S.' },
  { txt: 'Wallis and Futuna' },
  { txt: 'Western Sahara' },
  { txt: 'Yemen' },
  { txt: 'Zambia' },
  { txt: 'Zimbabwe' },
]